FILESEXTRAPATHS_prepend := "${THISDIR}/files:"

SRC_URI += "file://uvc.cfg"
#SRC_URI += "file://librealsense_formats_${PN}_4.4.patch"
SRC_URI += "file://realsense-camera-formats_${PN}_4.4.patch"
SRC_URI += "file://realsense-hid_${PN}_4.4.patch"
SRC_URI += "file://realsense-metadata_${PN}_4.4.patch"
SRC_URI += "file://0001-HID_SENSOR_CUSTOM_SENSOR-is-required-to-provide-RS4XX.patch"
SRC_URI += "file://01-xhci-Add-helper-to-get-hardware-dequeue-pointer-for.patch"
SRC_URI += "file://02-xhci-Add-stream-id-to-to-xhci_dequeue_state-structur.patch"
SRC_URI += "file://03-xhci-Find-out-where-an-endpoint-or-stream-stopped-fr.patch"
SRC_URI += "file://04-xhci-remove-unused-stopped_td-pointer.patch"
